<?php
$urlArray = $this->urlArray;
$urlArray['action'] = 'create';

printf((is_string($this->headlineFormat)) ? $this->headlineFormat : '<h1>%2$s %3$s %1$s</h1>',
    $this->typeName,
    $this->verb,
    preg_match("#^h?[aeiouäüö]+#ui", $this->typeName) ? 'an' : 'a');
if($this->message)
{
    echo '<p class="message">'.$this->message.'</p>';
}
echo $this->editingLanguageSwitch(
    $this->editLang,
    $urlArray,
    'modules_i18n',
    $this->editLangKey
);
$urlCreate = $urlArray;
$urlCreate[$this->editLangKey] = $this->editLang;
$url = $this->url($urlCreate, 'modules_i18n', True);

$this->form->setAction($url)
    ->output();

if('development' === APPLICATION_ENV && $this->dump)
{
    ?><div class="development">
    <h3>development information</h3>
    <div class="content">
    <?php echo GC_Debug::dump($this->dump,true); ?>
    </div></div>
    <?php
}