<?php

/**
 * DcDiary
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class DcDiary extends BaseDcDiary
{
    public function setTimestamp($timestamp)
    {
        $val = Doctrine_Validator::getValidator('timestamp');
        //if it does not validate it fail leter
        //if it validates we can use the timestamp
        if($val->validate($timestamp))
        {
            $date = new DateTime($timestamp , new DateTimeZone(Zend_Registry::get('config')->timezone));
            $date->setTimezone(new DateTimeZone(date_default_timezone_get()));
            $timestamp = $date->format('Y-m-d H:i:s');
            //alternate: $timestamp = date('Y-m-d H:i:s', $date->format('U'));
        }
        return $this->_set('timestamp', $timestamp);
    }
    public function getTimestamp($timestamp)
    {
        $timestamp = $this->_get('timestamp');
        if(!$timestamp)
        {
            return $timestamp;
        }
        //$timestamp = strtotime($timestamp);
        $date = new Zend_Date($timestamp, Zend_Date::ISO_8601);
        $date->setTimeZone(Zend_Registry::get('config')->timezone);
        //Zend_Locale_Format::convertPhpToIsoFormat('Y-m-d H:i:s');
        return $date->get('yyyy-MM-dd HH:mm:ss');
    }
}
