<?php
$config = Zend_Registry::getInstance()->config->error_log;
$file = $config->file_path.'/'.date($config->filename_date_format).$config->file_suffix;
if($this->isJson)
{
    ob_start();
}
if(!is_file($file))
{
    touch($file);
    chmod($file, 0666);
}

$writer = new Zend_Log_Writer_Stream($file);
$formatter = new Zend_Log_Formatter_Simple(
    sprintf(
        join('%1$s',array(
            '%%timestamp%% %%priorityName%% (%%priority%%) %%message%% %%errorMessage%%',
            'REMOTE_ADDR: %%ip%%',
            'HTTP_REFERER: %%referer%%',
            'requested: %%request%%',
            '%%exception%%',
            '%%info%%',
            '%2$s%1$s')
        ),
        PHP_EOL, str_repeat('-',80))
    );
$writer->setFormatter($formatter);
$logger = new Zend_Log($writer);
if ('development' === APPLICATION_ENV)
{
    $writerFirebug = new Zend_Log_Writer_Firebug();
    $logger->addWriter($writerFirebug);
}
$req = $this->request->getParams();
unset($req['error_handler']);
$log = array(
    'ip' => $this->request->getServer('REMOTE_ADDR'),
    'referer' => $this->request->getServer('HTTP_REFERER'),
    'request' => trim(html_entity_decode(strip_tags(GC_Debug::dump($req)))),
    'errorMessage' => $this->exception->getMessage(),
    'info' => '',
    'exception' => ''
);
if(!in_array($this->errorCode, array(403, 404)))
{
    //don't need a backtrace and all that stuff here
    $log['exception'] = $this->exception;
}
$logger->log($this->exception->getCode(), Zend_Log::ERR, $log);
?>

<div class="contentContainer">
  <h1><?php echo $this->message; ?></h1>

</div>

<?php
if ('development' === APPLICATION_ENV)
{
    //$layout = Zend_Layout::getMvcInstance();
    //if ($layout instanceof Zend_Layout) {
    //    $layout->disableLayout();
    //}
    //<h3>Request Parameters:</h3>
    //
    //<pre></pre>?php GC_Debug::dump($this->request->getParams()); ?/></pre>
    //
    ?>
    <h3>Exception information: <?php echo get_class($this->exception); ?></h3>
    <p><?php echo $this->exception->getMessage(); ?></p>
    <h3>Stack trace:</h3>
    <pre><?php echo $this->exception->getTraceAsString(); ?></pre>
<?php } ?>


<?php

//adding scripts
//these start the application
//$this->headScript()->appendFile('/graphicore/public/javascript/jquery/jquery-1.3.2.js','text/javascript');
//$this->headScript()->appendFile('/graphicore/public/javascript/main.js','text/javascript');

//GC_Debug::Dump($this->dump,true);

//if($this->renderSubMenu)
//{


/*
    $submenu = $this->navigation()
            ->mainmenu()
            ->renderMenu(Null,
            array(
                'indent'           => Null,
                'ulClass'          => 'submenu',
                'minDepth'         => 1,
                'maxDepth'         => null,
                'onlyActiveBranch' => true,
                'renderParents'    => false
        ));

*/
if($this->isJson)
{
    //Zend_Json::encode($this->daten);
    $daten = array
    (
        'title'   => $this->title($this->titleData),
        'languageSwitch' => $this->languageSwitch($this->urlArray),
        'type' => $this->resourceType,
        'html' => trim(ob_get_clean()),
    );
    if($this->ajaxMainMenu)
    {
        $daten['mainMenu'] = (string) $this->getMainMenu();
    }
    echo $this->json($daten);
}


