<?php
$translate = GC_Translate::get();
$request = Zend_Controller_Front::getInstance()->getRequest();
$baseUrl = $request->getBaseUrl();
// application/layouts/scripts/layout.phtml
echo '<'.'?xml version="1.0" encoding="UTF-8" ?'.'>';
echo $this->doctype(); ?>
<html
    xmlns="http://www.w3.org/1999/xhtml"
    xml:lang="<?php echo GC_I18n::getLang();?>" lang="<?php echo GC_I18n::getLang();?>"
    <?php /*
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.w3.org/1999/xhtml
                http://www.w3.org/2002/08/xhtml/xhtml1-strict.xsd"
    */ ?>
    >
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <title><?php echo $this->title('Backend'); ?></title>
<?php
    $styleUrl = $baseUrl.'/style/backend/';
    $this->headLink()->appendStylesheet($styleUrl.'global.css');
    $this->headLink()->appendStylesheet($styleUrl.'gentium/style.css');
    echo $this->headLink();
    echo $this->headScript();
?>

    <!--[if lt IE 9]>
    <link type="text/css" rel="stylesheet" media="screen" href="<?php echo $styleUrl;?>ielt9.css" />
    <![endif]-->
    <!--[if lt IE 8]>
    <?php
    /*
    <link type="text/css" rel="stylesheet" media="screen" href="<?php echo $styleUrl;?>reset.css" />
    */
    ?>
    <link type="text/css" rel="stylesheet" media="screen" href="<?php echo $styleUrl;?>ielt8.css" />
    <![endif]-->

<?php
    $scriptUrlCommon = $baseUrl.'/js/';
    $imagesUrlCommon = $baseUrl.'/images/';
    $jscripts = array(
/*
            'jquery-1.4.2.min.js',
            'ui/jquery.ui.core.js',
            'ui/jquery.ui.widget.js',
            'ui/jquery.ui.mouse.js',
            'ui/jquery.ui.resizable.js',
            'ui/jquery.ui.position.js',
            'ui/jquery.ui.dialog.js',
            'jwysiwyg-0.8/jquery.wysiwyg.js',
            'backendMain.js',
*/
    );
    foreach($jscripts as $script)
    {
        printf('<script type="text/javascript" src="%1$s%2$s"></script>', $scriptUrlCommon, $script);
    }
    //these stylesheets are related to some javascript ui functionality and thus located there
    foreach(array(
/*
        'jwysiwyg-0.8/jquery.wysiwyg.css',
        'jwysiwyg-0.8/jquery.wysiwyg.modal.css',
        'ui/jquery.ui.all.css',
        'ui/jquery.ui.dialog.css'
*/

        ) as $style)
    {
        printf('<link rel="stylesheet" href="%1$s%2$s" type="text/css" />', $scriptUrlCommon, $style);
    }
?>
</head>
<body>
<div class="page">
<?php
    $anchorFormat = '<a href="%1$s">%2$s</a>';
    $anchorFormatActive = '<a href="%1$s" class="active">%2$s</a>';
    $urlArr = array(
        'module'     => 'backend',
        'controller' => Null,
        'action'     => 'index',
        'lang' => GC_I18n::getLang()
    );
    /*create the menu*/
    $menu = array(sprintf(
        $anchorFormat,
        $this->url(array(
            'module'     => 'default',
            'controller' => 'index',
            'action'     => 'index',
            'lang' => GC_I18n::getLang()
            ), 'modules_i18n', True),
        'graphicore.de'
    ));
    $menu = $this->backendMenu(array(
        'menu' => $menu,
        'anchorFormat' => $anchorFormat,
        'anchorFormatActive' => $anchorFormatActive,
        'urlArr' => $urlArr,
        'controllers' => array(
            array($translate->_('Users'), 'user'),
            array($translate->_('Groups'), 'group'),
            array($translate->_('Diary'), 'diary'),
            array($translate->_('Filters'), 'filter'),
            array($translate->_('Pages'), 'page'),
        ),
        'request' => array(
            'module' => $request->getModuleName(),
            'controller' => $request->getControllerName(),
            'action' => $request->getActionName()
        ),
    ));


    if(Zend_Registry::getInstance()->user)
    {
        $user = $translate->_('You are logged in as:');
        $controllers = array(
            array(Zend_Registry::getInstance()->userName, array('user', 'setup')),
            array($translate->_('logout'), array('user', 'logout')),
        );
    }
    else
    {
        $user = $translate->_('You are not logged in');
        $controllers = array(
            array($translate->_('Password Recovery'), array('user', 'recover')),
            array($translate->_('login'), array('user', 'login'), 'loginI18n'),
        );
    }

    $menu2 = $this->backendMenu(array(
        'anchorFormat' => $anchorFormat,
        'anchorFormatActive' => $anchorFormatActive,
        'urlArr' => $urlArr,
        'controllers' => $controllers,
        'request' => array(
            'module' => $request->getModuleName(),
            'controller' => $request->getControllerName(),
            'action' => $request->getActionName()
        ),
    ));

    /*create the header*/
    printf('<div class="header">%1$s <span class="user">%3$s</span> %2$s</div>',
        sprintf('<ul class="menu"><li>%1$s</li></ul>', join('</li><li>', $menu)),
        sprintf('<ul class="menu"><li>%1$s</li></ul>', join('</li><li>', $menu2)),
        $user
    );
?>
<?php echo $this->layout()->content ?>
</div>
</body>
</html>

